apiVersion: v1
kind: ServiceAccount
metadata:
  name: mex-vault-secret-reader
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mex-secret-store
spec:
  provider:
    vault:
      server: 'https://vault.k8s-dev-tools.rki.local'
      path: secrets/mex
      version: v2
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUhWakNDQmo2Z0F3SUJBZ0lURUFBQUFOMm1ON1pMd2VZcWdBQUFBQUFBM1RBTkJna3Foa2lHOXcwQkFRc0YKQURBL01SVXdFd1lLQ1pJbWlaUHlMR1FCR1JZRmJHOWpZV3d4RXpBUkJnb0praWFKay9Jc1pBRVpGZ055YTJreApFVEFQQmdOVkJBTVRDRk5WUWpBMExVTkJNQjRYRFRJME1ERXdNakUwTlRVek1sb1hEVEkxTURJd01qRTBOVFV6Ck1sb3dJakVnTUI0R0ExVUVBeE1YYXpoekxXUmxkaTEwYjI5c2N5NXlhMmt1Ykc5allXd3dnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ1NyVjhIc0NSbUZvYVQvaHRtVnhyd2E0YWszTkwxY1NweApwM2l3VWJPQjRDVnBTRjc0NFEzWitkWWI5ZFlMS3ZtRUtBQml6TXV1bkRnL1VpZTI3UmpXbWxMSXF3RE04MEhnCmxlaXdXakxzSlVZVW5uYy9mTVpyeWs1SEJNUWJ3WXlWUGlVd1dsUVd0QSt4UDc5NTRrRVFTMm50TWlQOWFtZTkKeDJQT3pjdzlJUDZwZXpHR2RrRDZackhjNHZXeDBVcW5jeEg5UVJ4Wk5pRGVtWTc2T0JyR3NpZmpUK0dhenEvTgpmQlgzamx0VEgxZnBFeXg2NC9DbHRWOVBxMisxV3Z1YzVnOEZMMjFXZkhJQ2M3WGp1a0Rrc3FHdFF2ZjhHWjR2Cnk2YWN2VnlTN3ExM1pkaDhEalRlUFczTWtKbTAzUFlpZitHMEc3NlVERGUrSEhKTVVMNVRBZ01CQUFHamdnUm0KTUlJRVlqQWRCZ05WSFE0RUZnUVVhTmNYQ1RkRkUwUkZCbWdMdTZLNEZYM3RNSGt3Z2dGVkJnTlZIUkVFZ2dGTQpNSUlCU0lJWGF6aHpMV1JsZGkxMGIyOXNjeTV5YTJrdWJHOWpZV3lDRFdzNGN5MWtaWFl0ZEc5dmJIT0NIbUZ5CloyOWpaQzVyT0hNdFpHVjJMWFJ2YjJ4ekxuSnJhUzVzYjJOaGJJSWZhbVZ1YTJsdWN5NXJPSE10WkdWMkxYUnYKYjJ4ekxuSnJhUzVzYjJOaGJJSWNjSGx3YVM1ck9ITXRaR1YyTFhSdmIyeHpMbkpyYVM1c2IyTmhiSUllYUdGeQpZbTl5TG1zNGN5MWtaWFl0ZEc5dmJITXVjbXRwTG14dlkyRnNnaDEyWVhWc2RDNXJPSE10WkdWMkxYUnZiMnh6CkxuSnJhUzVzYjJOaGJJSWZaR0ZuYzNSbGNpNXJPSE10WkdWMkxYUnZiMnh6TG5KcmFTNXNiMk5oYklJZGRISnAKYm04dWF6aHpMV1JsZGkxMGIyOXNjeTV5YTJrdWJHOWpZV3lDSjJwbGJtdHBibk10YzNSaFoybHVaeTVyT0hNdApaR1YyTFhSdmIyeHpMbkpyYVM1c2IyTmhiSUlYZVc5d1lYTnpMblJyY0c5akxtbDBNekl1YkdGaWIzSXdId1lEClZSMGpCQmd3Rm9BVVErQUtDZkJQdXRCSEN2NjVic2JvYUFBc3Rxa3dnZXdHQTFVZEh3U0I1RENCNFRDQjNxQ0IKMjZDQjJJYUJybXhrWVhBNkx5OHZRMDQ5VTFWQ01EUXRRMEVzUTA0OVUzVmlNRFF0UTBFc1EwNDlRMFJRTEVOTwpQVkIxWW14cFl5VXlNRXRsZVNVeU1GTmxjblpwWTJWekxFTk9QVk5sY25acFkyVnpMRU5PUFVOdmJtWnBaM1Z5CllYUnBiMjRzUkVNOWNtdHBMRVJEUFd4dlkyRnNQMk5sY25ScFptbGpZWFJsVW1WMmIyTmhkR2x2Ymt4cGMzUS8KWW1GelpUOXZZbXBsWTNSRGJHRnpjejFqVWt4RWFYTjBjbWxpZFhScGIyNVFiMmx1ZElZbGFIUjBjRG92TDNCcgphUzV5YTJrdWJHOWpZV3d2WTNKc0wxTlZRakEwTFVOQkxtTnliRENCL2dZSUt3WUJCUVVIQVFFRWdmRXdnZTR3CmdhVUdDQ3NHQVFVRkJ6QUNob0dZYkdSaGNEb3ZMeTlEVGoxVFZVSXdOQzFEUVN4RFRqMUJTVUVzUTA0OVVIVmkKYkdsakpUSXdTMlY1SlRJd1UyVnlkbWxqWlhNc1EwNDlVMlZ5ZG1salpYTXNRMDQ5UTI5dVptbG5kWEpoZEdsdgpiaXhFUXoxeWEya3NSRU05Ykc5allXdy9ZMEZEWlhKMGFXWnBZMkYwWlQ5aVlYTmxQMjlpYW1WamRFTnNZWE56ClBXTmxjblJwWm1sallYUnBiMjVCZFhSb2IzSnBkSGt3UkFZSUt3WUJCUVVITUFLR09HaDBkSEE2THk5d2Eya3UKY210cExteHZZMkZzTDJOeWJDOVRkV0l3TkMxRFFTNXlhMmt1Ykc5allXeGZVMVZDTURRdFEwRXVZM0owTUFzRwpBMVVkRHdRRUF3SUY0REE4QmdrckJnRUVBWUkzRlFjRUx6QXRCaVVyQmdFRUFZSTNGUWlCczlRSWhMeVNDb1ROCmp3NkV5YVVZZ3RHN2NWbmNzaUNGaThaK0FnRmtBZ0VoTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3IKQmdFRkJRY0RBakFuQmdrckJnRUVBWUkzRlFvRUdqQVlNQW9HQ0NzR0FRVUZCd01CTUFvR0NDc0dBUVVGQndNQwpNRVFHQ1NxR1NJYjNEUUVKRHdRM01EVXdEZ1lJS29aSWh2Y05Bd0lDQWdDQU1BNEdDQ3FHU0liM0RRTUVBZ0lBCmdEQUhCZ1VyRGdNQ0J6QUtCZ2dxaGtpRzl3MERCekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBVURBZ0hDK2EKbnV1Q29BUVdjZXdZYkp0T1hFRDB3VWtZc0xPQndOVTliN1NiNDN2QlFyT0h2UXJtc25jMERzYTE2b0JpdFU3Rwo4OHdxdVhVR2pkSjhUTEtJTlVmUDhEblhQZ3Fla2VlSlMvM3Uwb0dyQ1VHd2xjMHNieFprd0VNZWhQcFlmVFR3CjhzdWtucTYvcHFOYVVnNTlxQ25qczRwWnA5c1JpZTVaaldKOWpnU3Zyd0srVGg0SjVBSi8xUmdJbHNkczkxRE8KTHVyblhqay9rZzNkUWQ4Y2xHcHJ1c2FlMTFHbXhGS3BtVkpOS1RDYXpTUFlhL1BUOGdveFg2UFZwUUZ5VnlvYgptZnNUQTNPb2xoT3hNVE1LSy9jUkVkM2YveTNHV2dhZjBEbFA3amQ3bFlFZkh3SWtKazV0aEVJek9ENHJzL0xUCkpCTWFwUlExZmY3WVdBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      auth:
        kubernetes:
          mountPath: kubernetes
          role: mex-secrets-user
          serviceAccountRef:
            name: mex-vault-secret-reader
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mex-credentials
spec:
  refreshInterval: '10s'
  secretStoreRef:
    name: mex-secret-store
    kind: SecretStore
  target:
    name: mex-drop-api-key-database
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: mex-drop-api-key-database
