name: Testing

on:
  push:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: on
  PIP_NO_CLEAN: on
  PIP_NO_INPUT: on
  PIP_PREFER_BINARY: on
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1

      - name: Cache requirements
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Cache environment
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        env:
          cache-name: cache-environment
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('*.lock') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Setup python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.14

      - name: Start containers
        run: docker compose up --build --detach

      - name: Install requirements
        run: make install

      - name: Await service readiness
        run: docker compose up --wait --wait-timeout 600

      - name: Run test suite
        id: test
        env:
          # keep in sync with MEX_DROP_API_KEY_DATABASE in compose.yaml
          MEX_DROP_API_KEY_DATABASE: '{"mex":["mex"],"test":["test"],"other":["other"]}'
        run: make test

      - name: Show container logs
        if: failure()
        run: docker compose logs --no-color --timestamps

      - name: Upload screenshots
        if: always() && steps.test.outcome != 'skipped'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: playwright-screenshots-${{ github.run_id }}
          path: tests_*.png
          if-no-files-found: error
          retention-days: 10

      - name: Cleanup containers
        if: always()
        run: docker compose down --volumes --remove-orphans
