name: Testing

on:
  push:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: on
  PIP_NO_CLEAN: on
  PIP_NO_INPUT: on
  PIP_PREFER_BINARY: on
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1

      - name: Cache requirements
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Cache environment
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        env:
          cache-name: cache-environment
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('*.lock') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Setup python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.14

      - name: Install requirements
        run: make install

      - name: Run test suite
        env:
          MEX_DROP_API_KEY_DATABASE: '{"mex":["mex"],"test":["test"]}'
        run: |
          uv run drop &
          echo `date -Iseconds` INFO checking service readiness &&
          curl --connect-timeout 10 --retry 10 --retry-delay 10 --retry-all-errors http://localhost:8000/_system/check &&
          make test

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: playwright-screenshots-${{ github.run_id }}
          path: tests_*.png
          if-no-files-found: error
          retention-days: 10
